export const invoices = [
  {
    invoiceId: 1,
    invoiceFrom: {
      name: "Jana Leyla",
      email: "jana@gmail.com",
      city: "Nukus",
      country: "Uzbekistan",
      streetAddress: "Amir Temur Kochasi 91-uy",
      phoneNumber: "+998931112233",
      postCode: 198212,
      companyName: "Paymet Uz",
    },
    invoiceTo: {
      name: "Jahongir",
      email: "rjohongirmirzohong@gmail.com",
      city: "Namangan",
      country: "Uzbekistan",
      streetAddress: "Obod Ko'cha 26-yt",
      postCode: 100999,
      companyName: "Upwork",
    },
    billTo: {
      bankName: "Khamkorbank",
      country: "Uzbekistan",
      iban: "ETD95476213874685",
      swiftCode: "BR91905",
      amount: 2000,
    },
    serviceTitle: "Web development",
    services: [
      {
        id: 1,
        service: "Database design",
        serviceDescription: "designed database for my app",
        quantity: 2,
        price: 1000.0,
      },
      {
        id: 2,
        service: "Frontend",
        serviceDescription: "Connected API with UI and build awesome UI",
        quantity: 1,
        price: 600.0,
      },
      {
        id: 3,
        service: "Admin Pannel",
        serviceDescription: "Admin Panel Made with React",
        quantity: 2,
        price: 900.0,
      },
    ],

    total: 2000,
    note: "Thank you very much for your services, I'd like to work with you next time also",
    invoiceDate: {
      issuedAt: "2022-03-12",
      dueDate: "2022-03-31",
    },
    invoiceStatus: {
      isPaid: false,
      isDrafted: false,
      isOverDue: false,
      isSent: false,
      isPending: true,
      isDownloaded: false,
    },
  },
  {
    invoiceId: 2,
    invoiceFrom: {
      name: "Munisa",
      email: "munisa@gmail.com",
      city: "Andijan",
      country: "Uzbekistan",
      streetAddress: "Alisher Navoiy Kochasi 11-uy",
      phoneNumber: "+99891 909 09 99",
      postCode: 100000,
      companyName: "Munisa MCHJ",
    },
    invoiceTo: {
      name: "Alisher",
      email: "alisher@gmail.com",
      city: "Qoqn",
      country: "Uzbekistan",
      streetAddress: "Qodiriy Ko'cha 26-yt",
      postCode: 100999,
      companyName: "Upwork",
    },
    billTo: {
      bankName: "Khamkorbank",
      country: "Uzbekistan",
      iban: "ETD95476213874685",
      swiftCode: "BR91905",
      amount: 500,
    },
    serviceTitle: "Theme development",
    services: [
      {
        id: 1,
        service: "Developing Theme",
        serviceDescription: "designed database for my app",
        quantity: 2,
        price: 550.0,
      },
    ],

    total: 2000,
    note: "Thank you very much for your services, I'd like to work with you next time also",
    invoiceDate: {
      issuedAt: "2022-03-12",
      dueDate: "2022-03-31",
    },
    invoiceStatus: {
      isPaid: false,
      isDrafted: false,
      isOverDue: false,
      isSent: false,
      isPending: true,
      isDownloaded: false,
    },
  },
  {
    invoiceId: 3,
    invoiceFrom: {
      name: "Qodir",
      email: "qodir@gmail.com",
      city: "Fergana",
      country: "Uzbekistan",
      streetAddress: "Nazariy Kochasi 91-uy",
      phoneNumber: "+998931112233",
      postCode: 198212,
      companyName: "Qodir Uz BBT",
    },
    invoiceTo: {
      name: "Mubina",
      email: "mubina@gmail.com",
      city: "Tashkent",
      country: "Uzbekistan",
      streetAddress: "Sergeli Tupik 26-yt",
      postCode: 100999,
      companyName: "SDC",
    },
    billTo: {
      bankName: "Khamkorbank",
      country: "Uzbekistan",
      iban: "ETD95476213874685",
      swiftCode: "BR91905",
      amount: 10000,
    },
    serviceTitle: "UI/UX",
    services: [
      {
        id: 1,
        service: "Desinging and Architecting Complex Web App",
        serviceDescription: "Desinged architecture and look of the website",
        quantity: 2,
        price: 15000.0,
      },
    ],

    total: 10000.0,
    note: "Thank you very much for your services, I'd like to work with you next time also",
    invoiceDate: {
      issuedAt: "2022-03-01",
      dueDate: "2022-03-31",
    },
    invoiceStatus: {
      isPaid: false,
      isDrafted: false,
      isOverDue: false,
      isSent: false,
      isPending: true,
      isDownloaded: false,
    },
  },
];
